---
title: "Mini-Project 2"
author: "Ha Cao and Cathy Lee"
date: "October 20, 2018"
output:
  html_document:
    code_folding: hide
---
### Loading the data
```{r, include = FALSE}
library(tidyverse)
library(RColorBrewer)
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

### Wrangle the data
```{r}
# join the contributions and candidates tables by cand_id
contributions_2012 <- contributions %>% 
  inner_join(candidates, by = "cand_id") %>%
  filter(cand_election_yr == 2012) %>% # filter only elections in 2012
  filter(transaction_type == "24E") %>% # filter only advocating donations
  select(cand_party_affiliation, cand_id, transaction_amt, other_id) %>%
  group_by(cand_id) %>%
  summarize(N = n(),
            total_amt_per_can = sum(transaction_amt))
```

```{r}
# join contributions_2012 and house_elections tables by fec_id = cand_id
contributions_2012 <- contributions_2012 %>%
  inner_join(house_elections, by = c("cand_id" = "fec_id"))
nrow(contributions_2012)
```

```{r}
# calculate the total number of votes for each kind of votes
total_ge <- sum(contributions_2012$general_votes)
total_primary <- sum(contributions_2012$primary_votes)
total_runoff <- sum(contributions_2012$runoff_votes)
# calculate the percentage of votes each candidate has
contributions_2012_vote_percent <- contributions_2012 %>%
  mutate(ge_percent = general_votes/total_ge,
         primary_percent = primary_votes/total_primary,
         runoff_percent = runoff_votes/total_runoff)
```

### Make the first data graphic about the relationship between amount of advocating donations received and number of votes received
```{r}
# write a function to draw a graph for a given y variable (specifically different kinds of votes), 
# with x variable as total amount of advocating donations received by each candidate
draw_vote_graph <- function(y_var, color){
  contributions_2012_vote_percent %>% ggplot(aes(x = total_amt_per_can)) +
    geom_line(aes(y = y_var), col = color)  
}
```

```{r}
# call function to draw graphs for each kind of votes
draw_vote_graph(contributions_2012_vote_percent$ge_percent, rgb(224/255, 94/255, 135/255))
draw_vote_graph(contributions_2012_vote_percent$primary_percent, rgb(110/255, 158/255, 204/255))
draw_vote_graph(contributions_2012_vote_percent$runoff_percent, rgb(123/255, 83/255, 160/255))
```

```{r}
# because one candidate can receive multiple donations
# but only has one number of votes
# so we group by cand_id to find the total amount of money one candidate received
contributions_2012_per_party <- contributions_2012 %>%
  group_by(party) %>%
  summarize(num_can = n(),
            total_amt = sum(total_amt_per_can),
            mean_amt = mean(total_amt_per_can),
            total_votes = sum(general_votes), 
            mean_votes = mean(general_votes),
            num_win = sum(ifelse(ge_winner == "W", 1, 0))) %>%
  arrange(desc(total_votes))
```

## Make data graphic
```{r, warning = FALSE}
contributions_2012_per_party %>%
  ggplot(aes(x = reorder(party, -total_votes))) +
  geom_bar(aes(y = total_votes), stat = "identity", fill = rgb(108/255, 185/255, 209/255)) 
```

```{r}
contributions_2012_per_party %>%
  ggplot(aes(x = reorder(party, -total_votes))) +
  geom_bar(aes(y = total_amt), stat = "identity", fill = rgb(224/255, 132/255, 13/255)) 
```
